### PR TITLE
Use local jquery to avoid redirect issue

### PR DESCRIPTION
**Pull request by toddgardner**
Fix for #1164 

Fine with this not being accepted as people might not want to check in deps; but it does reduce network dependencies in the deprecated frontend.

### CODE REVIEW

**Comment by wsanchez** [comment]
I'm trying to avoid venturing 3rd-party code here because it mixes up licensing. The network dependency is only on the first time the server starts up; at that point it serves a caches copy to clients.

**Comment by chaoticbear** [comment]
@toddgardner  can you assign yourself to the issue for this? Assuming you're going to keep working on it. If not no pressure. Just a nudge so we can all know what each other are working on and avoid overlap.

**Comment by toddgardner** [comment]
> @toddgardner can you assign yourself to the issue for this? #1164 Assuming you're going to keep working on it. If not no pressure. Just a nudge so we can all know what each other are working on and avoid overlap.

I'm not sure if I can assign myself without being added to the repo

**Comment by toddgardner** [comment]
Closing this for something to avoid checking in jquery

**Pull request closed without merging**
